### ISSUE TITLE
RedPitaya timing code doesn't do time lapse.

### ISSUE THREAD

**Issue by NickHallPhysics** [MicronOxford/RedPitaya-DSP#13]
The Red Pitaya timing code returns 

NotImplementedError: only runs one at a time

if time lapse imaging is attempted,

**Comment by carandraug** [comment]
> This is not a cockpit issue - should we close it?

Now transferred from cockpit to RedPitay-DSP repo.

**Comment by carandraug** [comment]
I've looked at cases where `numReps` is greather than one. That's for time series experiments when the executor has control over all devices used during a single repetition. This is the action table that is sent to the remote executor for a time series (3 second interval) and a single z plane:

```
(0.0, (18, [19894.857142857134, 214123.27619047617]))
(100.0, (16, [19894.857142857134, 214123.27619047617]))
(100.0000000001, (16, [19894.857142857134, 214123.27619047617]))
(100.0500000001, (16, [19894.857142857134, 214123.27619047617]))
(100.1000000001, (16, [19894.857142857134, 214123.27619047617]))
(3000.0, (16, [19894.857142857134, 214123.27619047617])) # 3 second wait
```

There is a 3 second wait action at the end. If we just repeat the table, then that wait action will happen on the last repeat (ok for 3 seconds, not ok for 1-2 hours time steps).

When rep duration is set to zero, then there is no wait action at all:

```
(0.0, (18, [19894.857142857134, 214123.27619047617]))
(100.0, (16, [19894.857142857134, 214123.27619047617]))
(100.0000000001, (16, [19894.857142857134, 214123.27619047617]))
(100.0500000001, (16, [19894.857142857134, 214123.27619047617]))
(100.1000000001, (16, [19894.857142857134, 214123.27619047617]))
```

**Comment by carandraug** [comment]
I have pushed a changed to the redpitaya branch on my fork that implements numReps greater than one. I have also deployed it on our own redpitaya for CryoSIM.

mentioning @iandobbie now because while this appears reported by Nick, it was actually reported by ian using Nick's account on the CryoSIM systems.
