### ISSUE TITLE
transfer ownership

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/RedPitaya-DSP#4]
Hi Tom, could you transfer this repo to us? The way it's done, had Micron's as a fork so we didn't even had the issues there.

**Comment by coralmw** [comment]
Yes, of course, should I transfer it to you/Mick/micron org account?

**Comment by carandraug** [comment]
On 22 May 2018 at 16:03, tomparks <notifications@github.com> wrote:
>
> Yes, of course, should I transfer it to you/Mick/micron org account?

To Micron's org account would be ideal.  Thank you

**Comment by coralmw** [comment]
Couple of problems! "MicronOxford/RedPitaya-DSP already exists and You don’t have the permission to create repositories on MicronOxford".

I don't know what the ideal solution is, but if we want the MicronOxford repository to not be a fork it might be best to
1) delete MicronOxford/RedPitaya-DSP
2) push from a local repo to MicronOxford/RedPitaya-DSP, creating it anew with whatever history that repository has.

Thoughts?

**Comment by carandraug** [comment]
On 22 May 2018 at 16:14, tomparks <notifications@github.com> wrote:
>
> Couple of problems! "MicronOxford/RedPitaya-DSP already exists

I thought Github would merge them automatically.  Anyway, I deleted
Micron's fork.

> and
> You don’t have the permission to create repositories on
> MicronOxford".

I just sent you an invitation to join the group.

> I don't know what the ideal solution is, but if we want the MicronOxford repository to not be a fork it might be best to
>
> delete MicronOxford/RedPitaya-DSP
> push from a local repo to MicronOxford/RedPitaya-DSP, creating it anew with whatever history that repository has.
>
> Thoughts?

The idea was to also keep the open issues you have.  Also, transfering
ownership means old urls to your repo will be redirected accordingly.

**Comment by coralmw** [comment]
Makes sense, done. It's under the sysadmin team right now, I figured if there was a permissions structure the members of that team would be able to set it up correctly.

**Comment by carandraug** [comment]
> Makes sense, done. It's under the sysadmin team right now, I figured if there was a permissions structure the members of that team would be able to set it up correctly.

That's perfect. I'll take it from here. Thank you. And do comment on the renaming of the project too if you have a preference.
